const array1 = [1, 2, 3, 4];

// 0 + 1 + 2 + 3 + 4
const initialValue = 0;
// accumulator at first takes the value given as intializer(,intilavalue)
// and afterwards it takes reult generated by that function as accumulator

// using basic function
const sumWithInitial=array1.reduce(function(acc,val){
    console.log(`${acc} : ${val}`);
    return acc+val
},0)

// using arrow funtion
// const sumWithInitial = array1.reduce((accumulator, currentValue) => accumulator + currentValue, initialValue);

// console.log(sumWithInitial);
// Expected output: 10


const shoppingCart = [
    {
        itemName: "js course",
        price: 2999
    },
    {
        itemName: "py course",
        price: 999
    },
    {
        itemName: "mobile dev course",
        price: 5999
    },
    {
        itemName: "data science course",
        price: 12999
    },
]

const priceToPay = shoppingCart.reduce((acc, item) => acc + item.price, 0)

console.log(priceToPay);